languageCode = "en-US"
baseURL = "https://benfrankel.me/"
title = "Shot in the Dark"
author = "Ben Frankel"
theme = "butter"
contentDir = "content"
layoutDir = "layouts"
publishDir = "site/debug"
disqusShortname = ""
canonifyURLs = true
pluralizeListTitles = false
pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
tag = "tags"
category = "categories"

[permalinks]
blog = "blog/:slug/"

[params]
dateForm = "Jan 2, 2006"
dateFormFull = "Jan 2, 2006: Mon (15:04:05 MST)"
description = "A blog about math, computers, puzzles, math puzzles, computer puzzles, and computer math."
copyrightNotice = "Copyright 2018 - Ben Frankel"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0/"
logoFile = "img/logo.svg"
faviconFile = "img/favicon.png"
github = "benfrankel"
linkedin = "benfrankel"
email = "ben.frankel7@gmail.com"
# issoHost = "comments.domain.tld:1234"
# githubRepo = "benfrankel/my-portfolio"
navigation = [
    ["blog", "blog"],
    ["projects", "projects"],
    ["puzzles", "puzzles"],
    ["about", "about"],
    ["résumé", "doc/resume.pdf"],
]

[params.fonts]
import = [
    "Pacifico",
    "Raleway:300,300i",
    "Merriweather:300,300i,700,700i",
    "Inconsolata:400,600",
]
local = []
default = "Merriweather, Georgia, 'Times New Roman'"
title = "Raleway, 'Helvetica Neue', Helvetica, Verdana"
header = "Merriweather, Verdana, 'Helvetica Neue', Helvetica, Arial"
code = "Inconsolata, 'Ubuntu Mono'"

[params.color]
# background = "#ffffff"
# link = "dodgerblue"
# linkHover = "inherit"
# header = "#303048"
# default = "#31353a"
# quote = "#7a7e82"
