languageCode = "en-US"
baseurl = "https://benfrankel.me/"
title = "Shot in the Dark"
author = "Ben Frankel"
theme = "cocoa-eh"
contentdir = "content"
layoutdir = "layouts"
publishdir = "site/debug"
disqusshortname = ""
canonifyurls = true
pluralizelisttitles = false

[taxonomies]
tag = "tags"
category = "categories"

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Jan 2, 2006: Mon (15:04:05 MST)"
description = "A blog about math, computers, puzzles, math puzzles, computer puzzles, and computer math."
copyright = "Copyright © 2018 Ben Frankel"
copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/logo.png"
faviconfile = "img/favicon.png"
highlightjs = true
progressively = false
share = false
latestpostcount = 6
github = "benfrankel"
linkedin = "benfrankel"
email = "ben.frankel7@gmail.com"
social_banner = "img/logo.png"
usesmallsummarycard = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "benfrankel/my-portfolio"
small_banner_logo = false

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
