languageCode = "en-US"
baseURL = "https://benfrankel.me/"
title = "Shot in the Dark"
theme = "butter"
contentDir = "content"
layoutDir = "layouts"
publishDir = "site/debug"
disqusShortname = ""
canonifyURLs = true
pluralizeListTitles = false
pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
tag = "tags"
category = "categories"

[permalinks]
blog = "blog/:slug/"

[params]
description = "A blog about math, computers, puzzles, math puzzles, computer puzzles, and computer math."
author = "Ben Frankel"
dateForm = "Jan 2, 2006"
dateFormFull = "Jan 2, 2006: Mon (15:04:05 MST)"
copyrightNotice = "Copyright 2018 - Ben Frankel"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0/"
attributionNotice = "Powered by Hugo"
attributionURL = "/powered-by-hugo/"
logoFile = "img/logo.svg"
faviconFile = "img/favicon.png"
github = "benfrankel"
linkedin = "benfrankel"
email = "ben.frankel7@gmail.com"
# issoHost = "comments.domain.tld:1234"
# githubRepo = "benfrankel/my-portfolio"
navigation = [
    ["blog", "blog"],
    ["projects", "projects"],
    ["puzzles", "puzzles"],
    ["about", "about"],
    ["résumé", "doc/resume.pdf"],
]

[params.fonts]
import = [
    "Merriweather:300,300i,700,700i",
    "Inconsolata:400,600",
    "Open Sans:300,400,700",
]
local = []
default = "Merriweather, Georgia, 'Times New Roman', serif"
title = "'Open Sans', 'Helvetica Neue', Helvetica, Arial, Verdana, sans-serif"
navigation = "'Open Sans', 'Helvetica Neue', Helvetica, Arial, Verdana, sans-serif"
header = "'Open Sans', 'Open Sans', 'Helvetica Neue', Helvetica, Arial, Verdana, sans-serif"
code = "Inconsolata, 'Ubuntu Mono', monospace"

[params.color]
# background = "#fff"
# regionBackground = "#fafafa"
# regionBorder = "#eee"
# default = "#202050"
# header = "#336"
# link = "dodgerblue"
# linkHover = "inherit"
# icon = "#889"
# iconHover = "#449"
# code = "#c25"
# codeLink = "#428bca"
# codeBackground = "#f8e8ea"
# codeBorder = "#ecd"
# codeShowBorder = true
# codeBlock = "inherit"
# codeBlockBackground = "#fafafa"
# codeBlockBorder = "#eee"
# codeBlockShowBorder = false
# quote = "#787886"
# quoteBackground = "#ffb"
# quoteBorder = "#fafaaf"
# quoteShowBorder = true
# separator = "#e9e9e9"
# footnoteList = "#666"
# footnoteLink = "dodgerblue"
